#SPDX-License-Identifier: MIT-0
---
# tasks file for addsudoer
- name: add /etc/sudoers.d/ entry
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ item }}
    content: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -csf %s'
  loop: '{{ sudoer_name }}'
  loop_control:
    label: "{{ item }}"
