#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: 'root'
    group: 'root'
    force: true

#- name: De-armor Docker GPG
#  ansible.builtin.command: gpg --dearmor --yes --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
#  args:
#    creates: /etc/apt/keyrings/docker.gpg owner=root group=root mode=644

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_extra_packages }}"
  loop_control:
    label: "{{ item }}"

- name: Check service status
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Get hardware name
  ansible.builtin.command: uname -m
  register: uname_result
  changed_when: false

- name: Append {{ docker_user }} to docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true

- name: Get docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v{{ docker_compose_ver }}/docker-compose-Linux-{{ uname_result.stdout }}
    dest: /usr/bin/docker-compose
    mode: "0755"
