#SPDX-License-Identifier: MIT-0
---
- name: Change hostname
  ansible.builtin.hostname:
    name: abyrvalg

- name: Change entry in /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(\s+)[a-z]{4}amethyst(\s+.*)?$'
    replace: '\1abyrvalg\2'
